config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :photos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :date, presence: true
  validates :image, presence: true
  validate :image_size_validation
  mount_uploader :image, ImageUploader

private
  def image_size_validation
    errors[:image] << "should be less than 5MB" if image.size > 5.megabytes
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authorize_user

  def index
    @photos = []
    Photo.find_each do |photo|
      if photo.user == current_user
        @photos << photo
      end
    end

    @todays_photo = one_photo_per_day
  end

  def show
    set_photo
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user = current_user
    @photo.date = Date.current

    if !one_photo_per_day.nil?
      flash.now[:notice] = "You can only submit one photo per day"
      render :new
      return
    end

    if @photo.save
      flash[:notice] = "Photo was successfully submitted."
      redirect_to photo_path(@photo)
    else
      flash[:notice] = @photo.errors.full_messages.join(", ")
      render :new
    end

  end

  def edit
    set_photo
  end

  def update
    set_photo
    if @photo.update_attributes(photo_params)
      flash[:notice] = "Your photo has been updated!"
      redirect_to photo_path
    else
      flash[:notice] = @photo.errors.full_messages.join(", ")
      render :new
    end
  end

  def destroy
    set_photo
    @photo.destroy

    redirect_to photos_path
  end

  private
    def authorize_user
      if !user_signed_in?
        flash[:notice] = "You do not have access to this page.  Please sign up or sign in."
        redirect_to root_path
      end
    end

    def one_photo_per_day
      Photo.find_by(
        user_id: current_user,
        date: Date.current
      )
    end

    def set_photo
      @photo = Photo.find(params[:id])
    end

    def photo_params
      params.require(:photo).permit(:description, :image, :user, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homes/index.html.erb
<div class='main-index'>
  <div class="small-6 columns">
    Upload one photo for the day. </br>
    Please sign in or sign up.</br>
    Then, click below to upload a new photo or view your photo for the day. </br></br>
    <%= link_to "Today's Photo", photos_path %> ||
    <%= link_to 'New Photo', new_photo_path %>
  </div>

  <div class="small-6 columns">
    <img src="https://i.imgur.com/shdA8O4.jpg" >
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photo A Day</title>
    <%= stylesheet_link_tag "application", media: 'all' %>
    <%= javascript_include_tag "vendor/modernizr" %>

    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar">
      <ul class="title-area">
        <li class="name">
          <h1><a href="/">Photo A Day</a></h1>
        </li>
      </ul>

      <section class="top-bar-section">
        <ul class="right">
          <%- if current_user -%>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <%- else -%>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
          <%- end -%>
        </ul>
      </section>
    </nav>

    <%- flash.each do |key, value| -%>
      <div class="flash flash-<%= key %>">
        <%= value %>
      </div>
    <%- end -%>

    <%= yield %>

    <%= javascript_include_tag "application" %>

    <%= yield :extra_footer %>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_for @photo do |f| %>
  <div class="field">
    <%= f.text_area :description %>
    <%= f.label :description, class: 'form-labels' %> <br />
  </div>

  <div class="field">
    <%= f.file_field :image %>
    <%= f.label :image, class: 'form-labels' %> <br />
  </div>

  <div class="actions">
    <%= f.submit "Submit Today's Photo", :class => "form-buttons" %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<div class="form">
<div class="heading">
  <%= "Edit Photo" %>
</div></br>
<%= render 'form' %>
</div>

app/views/photos/index.html.erb
<div class="photo-index">
  <div class="small-9 columns" style="border-right: 10px solid #82B6D5; border-width:10px;">
    <div class="center">
      Your Daily Photo </br>
    </div>

    <% if @todays_photo.nil? %>
      <div class="no-photo">
        </br><%= "You haven't uploaded a photo today." %></br>
        <%= "Click below to add a new photo." %></br></br>
        <%= link_to "New Photo", new_photo_path, class: "new-photo" %>
      </div>
    <% else %>
      <%= image_tag @todays_photo.image_url %></br>
      <%= "Photo Description: #{@todays_photo.description}" %>
    <% end %>
  </div>

  <div class="small-3 columns">
    <%= "Previous Photos:" %>
    <% if @photos.empty? %>
      <div class="previous-photos">
        <%= "You don't have any photos yet!" %>
      </div>
    <% else %>
      <% @photos.each do |photo| %>
        <%= link_to photo.date, photo_path(photo), class: "previous-photos" %></br>
      <% end %>
    <% end %>
  </div>
</div>

app/views/photos/new.html.erb
<div class="form">
  <div class="heading">
    <%= "New Photo" %>
  </div></br>

    <%= render 'form', photo: @photo%></br>

    <%= link_to 'Back to Photos', photos_path, class: "back"%>
</div>

app/views/photos/show.html.erb
<div class="show-heading"><%= "Photo of the Day (#{@photo.date})" %></div></br>
  <div class="row">
    <%= image_tag @photo.image_url %></br></br>
    <div class="small-6 column show">
      <%= "Photo Description: #{@photo.description}" %></br></br>
    </div>
    <div class="small-6 column show-buttons">
      <%= link_to 'Edit', edit_photo_path(@photo) %> ||
    <%= link_to 'Delete', @photo, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>